### ISSUE TITLE
Uninstall plugin

### ISSUE THREAD

**Issue by dynek** [xiezhenye/mysql-plugin-disable-myisam#5]
Hello,

First of all, thank you for the plugin. Nice idea :-)

For some reason, I had to uninstall your plugin but when I do so, connection to mysql is lost .. looks like it's crashing:

mysql> uninstall plugin disable_myisam;
ERROR 2013 (HY000): Lost connection to MySQL server during query

Can't really say why, would you happen to have an idea ?

Thank you

**Comment by rwagnergit** [comment]
FYI, I had this same problem if I installed the plugin using the my.cnf option: plugin-load="disable_myisam=disable_myisam.so" and then attempting to unload it with the SQL statement: UNLOAD PLUGIN DISABLE_MYISAM.  However, if I install the plugin with the SQL statement: INSTALL PLUGIN DISABLE_MYISAM SONAME 'disable_myisam.so', then I can successfully uninstall it with UNLOAD PLUGIN DISABLE_MYISAM.

So I think as long as you load the plugin using the SQL statement, you should be able to unload it.

**Comment by rwagnergit** [comment]
I have run into this problem, as well.  The problem only occurs if the plugin loads at mysqld startup.  For example, the following will cause the error:

INSTALL PLUGIN DISABLE_MYISAM SONAME 'disable_myisam.so';
stop mysqld
start mysqld
mysql> UNINSTALL PLUGIN DISABLE_MYISAM;
ERROR 2013 (HY000): Lost connection to MySQL server during query

However, if we do not restart mysqld between the INSTALL and UNINSTALL, the error does not occur.

**Comment by rwagnergit** [comment]
Appears to be non-specific to this plugin.  I opened https://bugs.mysql.com/bug.php?id=77749.

**Comment by xiezhenye** [comment]
You do not have access to bug #77749. :(

an openned myisam tables after plugin loaded carries a handler point to an ha_myisam_disable_myisam_wrapper which will be unaccessable after the plugin uninstalled and cause crash. While no myisam table is openned before the uninstall operation, crash also occurred because of uninstall operation will access the mysql.plugin table.

I tried to hack the vtable of the handler to restore the origin vtable of ha_myisam to fix the problem.
